"""add code field to trains

Revision ID: 75aab94d32da
Revises: 307be54d2856
Create Date: 2026-07-02 14:29:23.507770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75aab94d32da'
down_revision: Union[str, Sequence[str], None] = '307be54d2856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trains', sa.Column('code', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'trains', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trains', type_='unique')
    op.drop_column('trains', 'code')
    # ### end Alembic commands ###
