"""add auth fields and hold_token

Revision ID: e3c5b5893dc7
Revises: b9a6142a611e
Create Date: 2026-07-08 16:00:47.138817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3c5b5893dc7'
down_revision: Union[str, Sequence[str], None] = 'b9a6142a611e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('hold_token', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'hold_token')
    # ### end Alembic commands ###
